apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-demo
  template:
    metadata:
      labels:
        app: go-demo
    spec:
      containers:
        - name: go-demo
          image: denvasyliev/go-demo-app:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: go-demo-config
          readinessProbe:
            httpGet: { path: "/", port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
