apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app
  namespace: demo
  labels:
    app: go-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-demo-app
  template:
    metadata:
      labels:
        app: go-demo-app
    spec:
      volumes:
        - name: cfg
          configMap:
            name: app-config
        - name: cache
          emptyDir: {}
      containers:
        - name: app
          image: paranoidlookup/demo-app:v1.0.3
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: cfg
              mountPath: /etc/app
              readOnly: true
            - name: cache
              mountPath: /var/cache/app
