apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
  namespace: demo
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: alpine:3
              command: ["sh", "-c", "echo backup && date"]