apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app
  namespace: demo
  labels:
    app: go-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-demo-app
  template:
    metadata:
      labels:
        app: go-demo-app
    spec:
      containers:
        - name: app
          image: paranoidlookup/demo-app:v1.0.3
          ports:
            - containerPort: 8080
          env:
            - name: VERSION
              value: "v1"
---
apiVersion: v1
kind: Service
metadata:
  name: go-demo-app
  namespace: demo
  labels:
    app: go-demo-app
spec:
  type: ClusterIP
  selector:
    app: go-demo-app
  ports:
    - name: http
      port: 80
      targetPort: 8080